### ISSUE TITLE
Bi-directional transliteration support

### ISSUE THREAD

**Issue by iwaszko** [dchaplinsky/translit-ua#7]
Would it be possible to add a way to convert from latin version back to UA/RU?

Thanks for otherwise great library :thumbsup:

**Comment by dchaplinsky** [comment]
Unfortunately for most of transliteration tables it's impossible to do reverse encoding because of ambiguity.

**Comment by iwaszko** [comment]
I see, anyway thank you for a quick response and I guess you could close this issue then.

Just out of curiosity, which of the transliteration tables could be reversed?

**Comment by tindzk** [comment]
Thanks for the library! I only looked into National 2010. The conversion was reversible for [all words](https://github.com/sparsetech/translit-scala/blob/master/shared/src/test/scala/translit/UkrainianSpec.scala#L102) I tested. The only limitation is that apostrophes and soft signs cannot be restored without a dictionary or language model.
