### ISSUE TITLE
different apostrophe support + incorrect transliteration after apostrophe

### ISSUE THREAD

**Issue by ojlena** [dchaplinsky/translit-ua#8]
Hello,
First of all thank you very much for your script, it's very helpful :)

While I was using it I noticed two areas of imporovements.
First - your script understand ' (\u0027) as apostprophe, while as far as I know the correct apostrophe is ’ (\u2019). Therefore the other one is not being transliterated (should be transliterated to nothing) and is left as it is which is incorrect.
Second - after apostrophe letters like я, ю, є, ї should be transliterated to ia, iu, ie, i while they are being transliterated to ya, yu, ye, yi (this transliteration should be used only at the beginning of a word, not inside a word). This occurs after both kind of apostrophe so ' and ’.
Here is the reference with examples: http://zakon1.rada.gov.ua/laws/show/55-2010-%D0%BF

Best regards,
ojlena

**Comment by enagorny** [comment]
According to wikipedia in unicode apostrophe could be defined with three characters `U+0027 ' apostrophe`, `U+2019 ’ RIGHT SINGLE QUOTATION MARK` and `U+02BC ʼ MODIFIER LETTER APOSTROPHE` https://en.wikipedia.org/wiki/Apostrophe#Unicode
For now lib supports only 0027 which is incorrect. We'll add new apostrophes soon.

Second - is bug as well lib treats apostrophes as delimiter between words thats why rules for the word beginning applied.
